import {
  Coordinates,
  CouncilAgentEvaluation,
  CouncilAgentStatus,
  CouncilAgentType,
  CouncilChallengeResponse,
  CouncilDisagreement,
  CouncilEvaluationResult,
  CouncilEvidenceArbitration,
  CouncilEvidenceItem,
  DecisionAuditLogRecord,
  DecisionFlipCondition,
  DecisionFlipResult,
  SourceDisagreementItem
} from '../types/orca.js';
import { localKnowledgeService } from './localKnowledgeService.js';
import { marineRegistry, DecisionRunModel } from '../models/marineModels.js';

export interface CouncilInputs {
  waveHeight: number;
  wavePeriod?: number;
  swellHeight?: number;
  windSpeed: number;
  windGusts?: number;
  currentVelocity: number;
  precipitation?: number;
  sst: number;
  chlorophyll: number;
  surfacePressure?: number;
  secondaryWaveHeight?: number;
  secondaryWindSpeed?: number;
}

export class CouncilService {
  public static readonly SCORING_MODEL_VERSION = 'ORCA-DET-2.1';

  private static auditLogs = new Map<string, DecisionAuditLogRecord>();

  /**
   * Evaluates a marine location using the 5 independent specialized reasoning modules
   * Section 3 & Section 4 Compliance:
   * A. Weather Agent
   * B. Ocean Agent
   * C. Ecosystem Agent
   * D. Risk / Safety Agent
   * E. Local Knowledge Agent
   */
  static evaluateCouncil(
    coordinates: Coordinates,
    inputs: CouncilInputs,
    zoneMeta?: { id?: string; name?: string },
    comparisonInputs?: { zoneB: { id: string; name: string; inputs: CouncilInputs } }
  ): CouncilEvaluationResult {
    const timestamp = new Date().toISOString();
    const decisionId = `DEC-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).substring(2, 6).toUpperCase()}`;

    // 1. Weather Agent
    const weatherEval = this.evaluateWeatherAgent(inputs, timestamp);

    // 2. Ocean Agent
    const oceanEval = this.evaluateOceanAgent(inputs, timestamp);

    // 3. Ecosystem Agent
    const ecosystemEval = this.evaluateEcosystemAgent(inputs, timestamp);

    // 4. Risk / Safety Agent
    const riskEval = this.evaluateRiskAgent(inputs, timestamp);

    // 5. Local Fisher / Koli Knowledge Agent
    const localKnowledgeEval = this.evaluateLocalKnowledgeAgent(coordinates, inputs, timestamp);

    const agents: Record<CouncilAgentType, CouncilAgentEvaluation> = {
      WEATHER: weatherEval,
      OCEAN: oceanEval,
      ECOSYSTEM: ecosystemEval,
      RISK: riskEval,
      LOCAL_KNOWLEDGE: localKnowledgeEval
    };

    // 6. Source Disagreement Detector (Section 8: Never silently average)
    const sourceDisagreement = this.detectSourceDisagreements(inputs, timestamp);

    // 7. Agent Disagreement Engine (Section 3: Independent reasoning without forced consensus)
    const disagreement = this.detectDisagreement(agents, inputs);

    // 8. Evidence Arbitration & Deterministic Fusion (Section 4: Not generated by Gemini)
    const arbitration = this.arbitrateEvidence(agents, inputs, sourceDisagreement);

    // 9. Why This Zone?
    const whyThisZone = this.generateWhyThisZone(agents);

    // 10. Why Not This Zone? (if comparison requested)
    let whyNotThisZone: CouncilEvaluationResult['whyNotThisZone'] = undefined;
    if (comparisonInputs?.zoneB) {
      whyNotThisZone = this.generateWhyNotThisZone(
        inputs,
        comparisonInputs.zoneB.inputs,
        comparisonInputs.zoneB.id,
        comparisonInputs.zoneB.name
      );
    }

    // 11. Record Reproducible Audit Record
    const auditRecord: DecisionAuditLogRecord = {
      decisionId,
      modelVersion: this.SCORING_MODEL_VERSION,
      timestamp,
      coordinates,
      zoneId: zoneMeta?.id ?? 'zone-alpha',
      zoneName: zoneMeta?.name ?? 'Candidate Sector Alpha',
      finalScore: arbitration.finalScore,
      confidence: arbitration.confidence,
      agreementLevel: arbitration.agreementLevel,
      decision: arbitration.decision,
      weights: {
        weather: 14,
        ocean: 18,
        ecosystem: 16,
        risk: 24,
        localKnowledge: 12
      },
      thresholds: {
        waveCalm: 1.3,
        waveModerate: 2.1,
        windOptimal: 20,
        windHazard: 32,
        chloroOptimal: 1.2,
        sstMin: 26.5,
        sstMax: 29.5
      },
      inputEvidence: { ...inputs },
      agentResults: {
        WEATHER: weatherEval.status,
        OCEAN: oceanEval.status,
        ECOSYSTEM: ecosystemEval.status,
        RISK: riskEval.status,
        LOCAL_KNOWLEDGE: localKnowledgeEval.status
      },
      auditSignature: `ORCA-SIG-${Buffer.from(JSON.stringify({ c: coordinates, s: arbitration.finalScore, v: this.SCORING_MODEL_VERSION, t: timestamp })).toString('base64').substring(0, 24)}`
    };

    this.auditLogs.set(decisionId, auditRecord);

    const decisionRunModel: DecisionRunModel = {
      id: decisionId,
      createdAt: timestamp,
      updatedAt: timestamp,
      decisionId,
      modelVersion: this.SCORING_MODEL_VERSION,
      timestamp,
      location: coordinates,
      zoneId: zoneMeta?.id ?? 'zone-alpha',
      finalScore: arbitration.finalScore,
      confidence: arbitration.confidence,
      agreementLevel: arbitration.agreementLevel,
      verdict: arbitration.decision,
      weights: auditRecord.weights,
      thresholds: auditRecord.thresholds,
      hasDisagreement: disagreement.hasDisagreement,
      auditSignature: auditRecord.auditSignature,
      provenance: 'ORCA Deterministic Council Arbiter v2.1'
    };
    marineRegistry.saveDecisionRun(decisionRunModel);

    return {
      zoneId: zoneMeta?.id ?? 'zone-alpha',
      zoneName: zoneMeta?.name ?? 'Candidate Sector Alpha',
      coordinates,
      timestamp,
      agents,
      disagreement,
      arbitration,
      sourceDisagreement: sourceDisagreement.length > 0 ? sourceDisagreement : undefined,
      whyThisZone,
      whyNotThisZone
    };
  }

  /**
   * Retrieve a saved reproducible decision audit record
   */
  public static getDecisionAudit(decisionId: string): DecisionAuditLogRecord | undefined {
    return this.auditLogs.get(decisionId);
  }

  /**
   * Specialist Module 1: Weather Agent
   */
  private static evaluateWeatherAgent(inputs: CouncilInputs, timestamp: string): CouncilAgentEvaluation {
    const wind = inputs.windSpeed;
    const gusts = inputs.windGusts ?? wind * 1.3;

    let status: CouncilAgentStatus = 'FAVORABLE';
    let scoreContribution = 14;
    let confidence = 94;
    const findings: string[] = [];
    const evidence: CouncilEvidenceItem[] = [];

    if (wind < 20) {
      findings.push(`Sustained wind at ${wind.toFixed(1)} km/h is well within safe operating envelope.`);
      evidence.push({
        metric: 'Sustained Wind Speed',
        value: Number(wind.toFixed(1)),
        unit: 'km/h',
        benchmark: '< 20 km/h (Optimal)',
        contribution: 8,
        status: 'POSITIVE',
        source: 'Open-Meteo High-Resolution Atmospheric Model',
        timestamp
      });
    } else if (wind <= 32) {
      status = 'CAUTION';
      scoreContribution = 5;
      findings.push(`Moderate breeze (${wind.toFixed(1)} km/h) requiring active helm management.`);
      evidence.push({
        metric: 'Sustained Wind Speed',
        value: Number(wind.toFixed(1)),
        unit: 'km/h',
        benchmark: '20-32 km/h (Moderate)',
        contribution: 3,
        status: 'NEUTRAL',
        source: 'Open-Meteo High-Resolution Atmospheric Model',
        timestamp
      });
    } else {
      status = 'UNFAVORABLE';
      scoreContribution = -12;
      findings.push(`High wind hazard (${wind.toFixed(1)} km/h) approaching gale threshold.`);
      evidence.push({
        metric: 'Sustained Wind Speed',
        value: Number(wind.toFixed(1)),
        unit: 'km/h',
        benchmark: '> 32 km/h (Hazardous)',
        contribution: -8,
        status: 'WARNING',
        source: 'Open-Meteo High-Resolution Atmospheric Model',
        timestamp
      });
    }

    evidence.push({
      metric: 'Peak Wind Gusts',
      value: Number(gusts.toFixed(1)),
      unit: 'km/h',
      benchmark: '< 30 km/h',
      contribution: gusts < 30 ? 4 : -4,
      status: gusts < 30 ? 'POSITIVE' : 'WARNING',
      source: 'Open-Meteo Atmospheric Model',
      timestamp
    });

    return {
      agent: 'WEATHER',
      agentName: 'Atmospheric & Wind Specialist',
      status,
      findings,
      evidence,
      scoreContribution,
      confidence,
      source: 'Open-Meteo Global GFS/ECMWF Blend',
      timestamp,
      dataFreshness: '< 15 mins (Live Numerical Weather Model)',
      limitations: ['Microscale coastal squalls (< 3km) may deviate from regional grid forecasts']
    };
  }

  /**
   * Specialist Module 2: Ocean Agent
   */
  private static evaluateOceanAgent(inputs: CouncilInputs, timestamp: string): CouncilAgentEvaluation {
    const wave = inputs.waveHeight;
    const current = inputs.currentVelocity;
    const period = inputs.wavePeriod ?? 6.5;

    let status: CouncilAgentStatus = 'FAVORABLE';
    let scoreContribution = 18;
    let confidence = 92;
    const findings: string[] = [];
    const evidence: CouncilEvidenceItem[] = [];

    if (wave < 1.3) {
      findings.push(`Significant wave height (${wave.toFixed(2)} m) indicates calm hydrodynamic state.`);
      evidence.push({
        metric: 'Significant Wave Height',
        value: Number(wave.toFixed(2)),
        unit: 'm',
        benchmark: '< 1.3 m (Calm)',
        contribution: 10,
        status: 'POSITIVE',
        source: 'Copernicus Marine / Open-Meteo Waves',
        timestamp
      });
    } else if (wave <= 2.1) {
      status = 'CAUTION';
      scoreContribution = 6;
      findings.push(`Moderate swell (${wave.toFixed(2)} m) requires small vessel caution.`);
      evidence.push({
        metric: 'Significant Wave Height',
        value: Number(wave.toFixed(2)),
        unit: 'm',
        benchmark: '1.3 - 2.1 m (Moderate)',
        contribution: 2,
        status: 'NEUTRAL',
        source: 'Copernicus Marine / Open-Meteo Waves',
        timestamp
      });
    } else {
      status = 'UNFAVORABLE';
      scoreContribution = -14;
      findings.push(`Hazardous sea state (${wave.toFixed(2)} m) with elevated vessel rolling.`);
      evidence.push({
        metric: 'Significant Wave Height',
        value: Number(wave.toFixed(2)),
        unit: 'm',
        benchmark: '> 2.1 m (Rough)',
        contribution: -12,
        status: 'WARNING',
        source: 'Copernicus Marine / Open-Meteo Waves',
        timestamp
      });
    }

    evidence.push({
      metric: 'Surface Current Velocity',
      value: Number(current.toFixed(2)),
      unit: 'km/h',
      benchmark: '< 2.0 km/h (Manageable)',
      contribution: current < 2.0 ? 5 : -4,
      status: current < 2.0 ? 'POSITIVE' : 'WARNING',
      source: 'Copernicus Marine Ocean Physics',
      timestamp
    });

    evidence.push({
      metric: 'Mean Wave Period',
      value: Number(period.toFixed(1)),
      unit: 's',
      benchmark: '5.0-9.0 s',
      contribution: 3,
      status: 'POSITIVE',
      source: 'Copernicus Marine / Open-Meteo Marine',
      timestamp
    });

    return {
      agent: 'OCEAN',
      agentName: 'Hydrodynamics & Sea State Specialist',
      status,
      findings,
      evidence,
      scoreContribution,
      confidence,
      source: 'Copernicus Marine Service / Open-Meteo Waves',
      timestamp,
      dataFreshness: '< 1 hour (Hydrodynamic Wave Model)',
      limitations: ['Nearshore bathymetric shoaling reflections require local radar verification']
    };
  }

  /**
   * Specialist Module 3: Ecosystem Agent
   */
  private static evaluateEcosystemAgent(inputs: CouncilInputs, timestamp: string): CouncilAgentEvaluation {
    const chloro = inputs.chlorophyll;
    const sst = inputs.sst;

    let status: CouncilAgentStatus = 'FAVORABLE';
    let scoreContribution = 16;
    let confidence = 89;
    const findings: string[] = [];
    const evidence: CouncilEvidenceItem[] = [];

    if (chloro >= 1.2) {
      findings.push(`Elevated primary biomass concentration (${chloro.toFixed(2)} mg/m³) indicates active foraging ground.`);
      evidence.push({
        metric: 'Chlorophyll-a Concentration',
        value: Number(chloro.toFixed(2)),
        unit: 'mg/m³',
        benchmark: '>= 1.2 mg/m³ (Productive)',
        contribution: 10,
        status: 'POSITIVE',
        source: 'Copernicus Sentinel-3 OLCI Ocean Colour',
        timestamp
      });
    } else if (chloro >= 0.6) {
      findings.push(`Moderate biomass (${chloro.toFixed(2)} mg/m³) suitable for pelagic schooling.`);
      evidence.push({
        metric: 'Chlorophyll-a Concentration',
        value: Number(chloro.toFixed(2)),
        unit: 'mg/m³',
        benchmark: '0.6-1.2 mg/m³ (Moderate)',
        contribution: 6,
        status: 'NEUTRAL',
        source: 'Copernicus Sentinel-3 OLCI Ocean Colour',
        timestamp
      });
    } else {
      status = 'CAUTION';
      scoreContribution = 3;
      findings.push(`Low chlorophyll concentration (${chloro.toFixed(2)} mg/m³) signals oligotrophic waters.`);
      evidence.push({
        metric: 'Chlorophyll-a Concentration',
        value: Number(chloro.toFixed(2)),
        unit: 'mg/m³',
        benchmark: '< 0.6 mg/m³ (Low)',
        contribution: -2,
        status: 'WARNING',
        source: 'Copernicus Sentinel-3 OLCI Ocean Colour',
        timestamp
      });
    }

    const isOptimalSst = sst >= 26.5 && sst <= 29.5;
    evidence.push({
      metric: 'Sea Surface Temperature',
      value: Number(sst.toFixed(1)),
      unit: '°C',
      benchmark: '26.5 - 29.5 °C (Pelagic Optimal)',
      contribution: isOptimalSst ? 6 : -3,
      status: isOptimalSst ? 'POSITIVE' : 'WARNING',
      source: 'Copernicus Sentinel-3 SLSTR / AVHRR SST',
      timestamp
    });

    findings.push(`Sea surface temperature (${sst.toFixed(1)}°C) matches commercial mackerel and sardine habitat preferences.`);

    return {
      agent: 'ECOSYSTEM',
      agentName: 'Marine Ecology & PFZ Specialist',
      status,
      findings,
      evidence,
      scoreContribution,
      confidence,
      source: 'Sentinel-3 OLCI Biomass & SLSTR Thermal Infrared',
      timestamp,
      dataFreshness: '< 3 hours (Satellite Earth Observation Pass)',
      limitations: ['Monsoon cloud cover can obscure optical and thermal satellite infrared bands']
    };
  }

  /**
   * Specialist Module 4: Risk & Safety Agent
   * Non-linear physical exposure formula:
   * Exposure = (Wave/3.2)^1.3 × 45 + (Wind/50)^1.2 × 35 + min(1, Current/3.5) × 20
   */
  private static evaluateRiskAgent(inputs: CouncilInputs, timestamp: string): CouncilAgentEvaluation {
    const wave = inputs.waveHeight;
    const wind = inputs.windSpeed;
    const current = inputs.currentVelocity;

    const rawRisk = Math.round(
      Math.pow(wave / 3.2, 1.3) * 45 +
      Math.pow(wind / 50, 1.2) * 35 +
      Math.min(1, current / 3.5) * 20
    );
    const riskScore = Math.min(100, Math.max(0, rawRisk));

    let status: CouncilAgentStatus = 'FAVORABLE';
    let scoreContribution = 12;
    let confidence = 93;
    const findings: string[] = [];
    const evidence: CouncilEvidenceItem[] = [];

    if (riskScore < 35) {
      findings.push(`Low total physical exposure index (${riskScore}/100); benign sea state profile.`);
      evidence.push({
        metric: 'Physical Exposure Index',
        value: riskScore,
        unit: '/100',
        benchmark: '< 35 (Low Risk)',
        contribution: 12,
        status: 'POSITIVE',
        source: 'ORCA Multi-Criteria Risk Matrix',
        timestamp
      });
    } else if (riskScore <= 55) {
      status = 'CAUTION';
      scoreContribution = -10;
      findings.push(`Elevated wave/wind interaction creates localized chop and dynamic vessel instability.`);
      evidence.push({
        metric: 'Physical Exposure Index',
        value: riskScore,
        unit: '/100',
        benchmark: '35-55 (Elevated Exposure)',
        contribution: -10,
        status: 'WARNING',
        source: 'ORCA Multi-Criteria Risk Matrix',
        timestamp
      });
    } else {
      status = 'UNFAVORABLE';
      scoreContribution = -24;
      findings.push(`Severe maritime risk profile (${riskScore}/100); small vessel departure discouraged.`);
      evidence.push({
        metric: 'Physical Exposure Index',
        value: riskScore,
        unit: '/100',
        benchmark: '> 55 (High Hazard)',
        contribution: -24,
        status: 'WARNING',
        source: 'ORCA Multi-Criteria Risk Matrix',
        timestamp
      });
    }

    evidence.push({
      metric: 'Hydrodynamic Sea Strain',
      value: Number((wave * (wind / 10)).toFixed(1)),
      unit: 'm·Bft',
      benchmark: '< 4.0 m·Bft',
      contribution: wave * (wind / 10) < 4.0 ? 3 : -6,
      status: wave * (wind / 10) < 4.0 ? 'POSITIVE' : 'WARNING',
      source: 'ORCA Maritime Safety Model',
      timestamp
    });

    return {
      agent: 'RISK',
      agentName: 'Maritime Safety & Risk Specialist',
      status,
      findings,
      evidence,
      scoreContribution,
      confidence,
      source: 'ORCA Operational Seamanship & Risk Engine',
      timestamp,
      dataFreshness: '< 10 mins (Continuous Hydrodynamic Strain Compute)',
      limitations: ['Vessel stability envelope assumes typical motorized craft (12-28m); skiffs face higher risk']
    };
  }

  /**
   * Specialist Module 5: Local Fisher / Koli Knowledge Agent
   * Section 5 Compliance: Combines local community ecological memory with scientific evidence
   */
  private static evaluateLocalKnowledgeAgent(
    coordinates: Coordinates,
    inputs: CouncilInputs,
    timestamp: string
  ): CouncilAgentEvaluation {
    const nearbyObs = localKnowledgeService.getObservationsNear(coordinates, 60);

    const findings: string[] = [];
    const evidence: CouncilEvidenceItem[] = [];
    let status: CouncilAgentStatus = 'FAVORABLE';
    let scoreContribution = 10;
    let confidence = 88;

    if (nearbyObs.length > 0) {
      const top = nearbyObs[0];
      findings.push(`Community marine report confirms ${top.observedProductivity?.toLowerCase() || 'active'} conditions targeting ${top.speciesOptional || 'pelagic species'}.`);
      evidence.push({
        metric: 'Local Community Marine Log',
        value: top.speciesOptional ? `${top.speciesOptional} (${top.observedProductivity})` : 'Active Marine Activity',
        unit: 'observation',
        benchmark: 'Favorable Field Report',
        contribution: top.observedProductivity === 'HIGH' ? 10 : 4,
        status: top.observedProductivity === 'LOW' ? 'WARNING' : 'POSITIVE',
        source: top.provenance,
        timestamp: top.observationTime
      });

      if (top.seaConditionOptional) {
        findings.push(`Observed sea state: "${top.seaConditionOptional}".`);
      }

      if (top.observedProductivity === 'LOW') {
        status = 'CAUTION';
        scoreContribution = -4;
      }
    } else {
      findings.push('Sector lies within historical Koli coastal migratory corridor with moderate seasonal baselines.');
      evidence.push({
        metric: 'Historical Community Basin Memory',
        value: 'Standard Autumn Corridor',
        unit: 'registry',
        benchmark: 'Baseline Pelagic Migration',
        contribution: 6,
        status: 'POSITIVE',
        source: 'Koli Coastal Fishermen Historical Knowledge Registry',
        timestamp
      });
    }

    return {
      agent: 'LOCAL_KNOWLEDGE',
      agentName: 'Local Fisher & Koli Ecological Knowledge Agent',
      status,
      findings,
      evidence,
      scoreContribution,
      confidence,
      source: 'Koli Community Marine Observations & Historical Memory',
      timestamp,
      dataFreshness: nearbyObs.length > 0 ? '< 24 hours (Verified Local Observation)' : 'Historical Baseline Record',
      limitations: ['Empirical artisanal observations; variations may occur depending on vessel gear and tide timing']
    };
  }

  /**
   * Section 8: Source Disagreement Detector
   * Detects variance between distinct sensor providers without silently averaging them
   */
  private static detectSourceDisagreements(inputs: CouncilInputs, timestamp: string): SourceDisagreementItem[] {
    const disagreements: SourceDisagreementItem[] = [];

    // Check wave height divergence if secondary provider telemetry is available
    if (inputs.secondaryWaveHeight !== undefined) {
      const diff = Math.abs(inputs.waveHeight - inputs.secondaryWaveHeight);
      if (diff >= 0.4) {
        disagreements.push({
          variable: 'Significant Wave Height',
          providerA: {
            name: 'Copernicus Marine Hydrodynamic Model',
            value: Number(inputs.waveHeight.toFixed(2)),
            unit: 'm',
            timestamp
          },
          providerB: {
            name: 'Open-Meteo High-Resolution Marine',
            value: Number(inputs.secondaryWaveHeight.toFixed(2)),
            unit: 'm',
            timestamp
          },
          difference: Number(diff.toFixed(2)),
          differenceUnit: 'm',
          impact: diff >= 0.6 ? 'High uncertainty in sea state boundary; Council adopts precautionary weighting' : 'Moderate model divergence within acceptable operational variance'
        });
      }
    }

    // Check wind speed divergence
    if (inputs.secondaryWindSpeed !== undefined) {
      const diff = Math.abs(inputs.windSpeed - inputs.secondaryWindSpeed);
      if (diff >= 7.0) {
        disagreements.push({
          variable: 'Sustained Wind Velocity',
          providerA: {
            name: 'ECMWF IFS Atmospheric Model',
            value: Number(inputs.windSpeed.toFixed(1)),
            unit: 'km/h',
            timestamp
          },
          providerB: {
            name: 'NOAA GFS Global Forecast System',
            value: Number(inputs.secondaryWindSpeed.toFixed(1)),
            unit: 'km/h',
            timestamp
          },
          difference: Number(diff.toFixed(1)),
          differenceUnit: 'km/h',
          impact: 'Atmospheric divergence detected across synoptic models'
        });
      }
    }

    return disagreements;
  }

  /**
   * Agent Disagreement Engine
   * Detects and explains divergences among the 5 specialized reasoning modules
   */
  static detectDisagreement(
    agents: Record<CouncilAgentType, CouncilAgentEvaluation>,
    inputs: CouncilInputs
  ): CouncilDisagreement {
    const statuses = Object.entries(agents).map(([type, evalItem]) => ({
      type: type as CouncilAgentType,
      status: evalItem.status
    }));

    const favorable = statuses.filter(s => s.status === 'FAVORABLE').map(s => s.type);
    const caution = statuses.filter(s => s.status === 'CAUTION').map(s => s.type);
    const unfavorable = statuses.filter(s => s.status === 'UNFAVORABLE').map(s => s.type);

    const dissentingAgents = [...caution, ...unfavorable];
    const concurringAgents = favorable;
    const hasDisagreement = dissentingAgents.length > 0 && concurringAgents.length > 0;

    let explanation = 'All 5 specialized reasoning modules unanimously concur on the environmental baseline.';
    const favorableFactors: string[] = [];
    const cautionaryFactors: string[] = [];

    if (hasDisagreement) {
      const concurringNames = concurringAgents.map(a => agents[a].agentName).join(', ');
      const dissentingNames = dissentingAgents.map(a => agents[a].agentName).join(', ');

      for (const a of concurringAgents) {
        if (agents[a].evidence[0]) {
          favorableFactors.push(`${agents[a].evidence[0].metric} (${agents[a].evidence[0].value} ${agents[a].evidence[0].unit})`);
        }
      }
      for (const a of dissentingAgents) {
        if (agents[a].evidence[0]) {
          cautionaryFactors.push(`${agents[a].evidence[0].metric} (${agents[a].evidence[0].value} ${agents[a].evidence[0].unit})`);
        }
      }

      if (dissentingAgents.length === 1 && dissentingAgents[0] === 'RISK') {
        explanation = `Four evidence domains support the sector (${concurringAgents.join(', ')}), while the Maritime Safety & Risk Specialist identifies elevated hydrodynamic exposure (${inputs.waveHeight.toFixed(1)}m wave / ${inputs.windSpeed.toFixed(0)} km/h wind).`;
      } else {
        explanation = `${concurringAgents.length} evidence domains indicate favorable operating factors (${concurringNames}), while ${dissentingAgents.length} specialist(s) (${dissentingNames}) flag environmental or localized caution.`;
      }
    }

    return {
      hasDisagreement,
      dissentingAgents,
      concurringAgents,
      explanation,
      evidenceContrast: {
        favorableFactors,
        cautionaryFactors
      }
    };
  }

  /**
   * Evidence Arbitration & Deterministic Fusion
   * Deterministic Formula: 50 + sum(scoreContributions). Never generated by Gemini.
   */
  static arbitrateEvidence(
    agents: Record<CouncilAgentType, CouncilAgentEvaluation>,
    inputs: CouncilInputs,
    sourceDisagreements: SourceDisagreementItem[] = []
  ): CouncilEvidenceArbitration {
    const totalContribution = Object.values(agents).reduce((acc, a) => acc + a.scoreContribution, 0);
    // Slight penalty if multi-provider source disagreement is high (precautionary principle)
    const disagreementPenalty = sourceDisagreements.length > 0 ? 3 : 0;
    const finalScore = Math.min(100, Math.max(0, 50 + totalContribution - disagreementPenalty));

    const totalConfidence = Math.round(
      Object.values(agents).reduce((acc, a) => acc + a.confidence, 0) / Object.keys(agents).length
    );

    const concurringCount = Object.values(agents).filter(a => a.status === 'FAVORABLE').length;
    const agreementLevel = `${concurringCount}/5 agents`;

    let decision: CouncilEvidenceArbitration['decision'] = 'FAVORABLE';
    if (finalScore >= 75 && concurringCount >= 4) {
      decision = 'FAVORABLE';
    } else if (finalScore >= 60 || concurringCount >= 3) {
      decision = 'CONDITIONALLY_FAVORABLE';
    } else if (finalScore >= 45) {
      decision = 'CAUTION';
    } else {
      decision = 'UNFAVORABLE';
    }

    const allEvidence: CouncilEvidenceItem[] = [];
    Object.values(agents).forEach(a => allEvidence.push(...a.evidence));

    const dominantFactors = allEvidence
      .filter(e => e.contribution > 0)
      .sort((a, b) => b.contribution - a.contribution)
      .slice(0, 3)
      .map(e => `${e.metric}: ${e.value} ${e.unit} (+${e.contribution} pts)`);

    const negativeFactors = allEvidence
      .filter(e => e.contribution < 0)
      .sort((a, b) => a.contribution - b.contribution)
      .slice(0, 3)
      .map(e => `${e.metric}: ${e.value} ${e.unit} (${e.contribution} pts)`);

    if (negativeFactors.length === 0) {
      negativeFactors.push('Zero critical hazards detected across sensor telemetry.');
    }

    const conflicts: string[] = [];
    if (agents.RISK.status === 'CAUTION' && agents.OCEAN.status === 'FAVORABLE') {
      conflicts.push('Ocean Agent confirms wave height is within limits, but Risk Agent identifies wind-wave interaction steepness.');
    }
    if (agents.ECOSYSTEM.status === 'FAVORABLE' && agents.WEATHER.status === 'UNFAVORABLE') {
      conflicts.push('High biomass productivity present, but atmospheric winds constrain safe craft transit.');
    }
    if (agents.LOCAL_KNOWLEDGE.status === 'FAVORABLE' && agents.RISK.status === 'CAUTION') {
      conflicts.push('Local community reports active fishing run, whereas numerical risk matrix flags swell exposure.');
    }
    for (const sd of sourceDisagreements) {
      conflicts.push(`Source Disagreement: ${sd.variable} differs by ${sd.difference} ${sd.differenceUnit} between ${sd.providerA.name} and ${sd.providerB.name}.`);
    }

    const evidenceChain = [
      { step: '1. Ingestion', detail: 'Telemetry ingested from Open-Meteo, Copernicus Sentinel-3 & Koli LEK Registry', status: 'VERIFIED' as const },
      { step: '2. Normalization', detail: 'Physical parameters normalized into standardized SI environmental units', status: 'VERIFIED' as const },
      { step: '3. Council Dispatch', detail: `5 independent reasoning agents evaluated sector (${agreementLevel})`, status: 'VERIFIED' as const },
      { step: '4. Disagreement Arbitration', detail: conflicts.length > 0 ? conflicts[0] : 'Telemetry and local observations demonstrated mutual convergence', status: conflicts.length > 0 ? 'CAUTION' as const : 'VERIFIED' as const },
      { step: '5. Deterministic Scoring', detail: `Arbiter version ${this.SCORING_MODEL_VERSION} computed final score of ${finalScore}/100 with ${totalConfidence}% confidence`, status: 'VERIFIED' as const }
    ];

    return {
      finalScore,
      confidence: totalConfidence,
      agreementLevel,
      decision,
      scoringModelVersion: this.SCORING_MODEL_VERSION,
      conflicts,
      dominantFactors,
      negativeFactors,
      evidenceChain
    };
  }

  /**
   * "What Would Flip The Decision?"
   * Computes the exact measurable threshold shifts needed for Zone B to overtake Zone A
   */
  static calculateDecisionFlip(
    zoneA: { id: string; name: string; inputs: CouncilInputs },
    zoneB: { id: string; name: string; inputs: CouncilInputs }
  ): DecisionFlipResult {
    const evalA = this.evaluateCouncil({ latitude: 0, longitude: 0, isMarine: true }, zoneA.inputs, { id: zoneA.id, name: zoneA.name });
    const evalB = this.evaluateCouncil({ latitude: 0, longitude: 0, isMarine: true }, zoneB.inputs, { id: zoneB.id, name: zoneB.name });

    const scoreA = evalA.arbitration.finalScore;
    const scoreB = evalB.arbitration.finalScore;

    const leader = scoreA >= scoreB ? { id: zoneA.id, name: zoneA.name, inputs: zoneA.inputs, score: scoreA } : { id: zoneB.id, name: zoneB.name, inputs: zoneB.inputs, score: scoreB };
    const trailer = scoreA >= scoreB ? { id: zoneB.id, name: zoneB.name, inputs: zoneB.inputs, score: scoreB } : { id: zoneA.id, name: zoneA.name, inputs: zoneA.inputs, score: scoreA };

    const scoreDifference = leader.score - trailer.score;
    const targetOvertakePoints = Math.max(2, scoreDifference + 2);

    const flipConditions: DecisionFlipCondition[] = [];

    // Condition 1: Wave deterioration at Leader
    const waveDelta = Number((targetOvertakePoints / 16).toFixed(2));
    const waveThreshold = Number((leader.inputs.waveHeight + waveDelta).toFixed(2));
    flipConditions.push({
      variable: 'Significant Wave Height at ' + leader.name,
      currentValue: Number(leader.inputs.waveHeight.toFixed(2)),
      flipThreshold: waveThreshold,
      delta: waveDelta,
      unit: 'm',
      description: `If significant wave height at ${leader.name} builds from ${leader.inputs.waveHeight.toFixed(2)}m to ${waveThreshold}m (+${waveDelta}m swell increase).`,
      impactScoreDelta: -targetOvertakePoints
    });

    // Condition 2: Wind speed deterioration at Leader
    const windDelta = Number((targetOvertakePoints / 0.8).toFixed(1));
    const windThreshold = Number((leader.inputs.windSpeed + windDelta).toFixed(1));
    flipConditions.push({
      variable: 'Wind Velocity at ' + leader.name,
      currentValue: Number(leader.inputs.windSpeed.toFixed(1)),
      flipThreshold: windThreshold,
      delta: windDelta,
      unit: 'km/h',
      description: `If sustained wind velocity at ${leader.name} rises from ${leader.inputs.windSpeed.toFixed(1)} km/h to ${windThreshold} km/h (+${windDelta} km/h wind stress).`,
      impactScoreDelta: -targetOvertakePoints
    });

    // Condition 3: Chlorophyll Surge at Trailer
    const chloroDelta = Number((targetOvertakePoints / 10).toFixed(2));
    const chloroThreshold = Number((trailer.inputs.chlorophyll + chloroDelta).toFixed(2));
    flipConditions.push({
      variable: 'Chlorophyll Biomass at ' + trailer.name,
      currentValue: Number(trailer.inputs.chlorophyll.toFixed(2)),
      flipThreshold: chloroThreshold,
      delta: chloroDelta,
      unit: 'mg/m³',
      description: `If pelagic chlorophyll biomass at ${trailer.name} intensifies from ${trailer.inputs.chlorophyll.toFixed(2)} to ${chloroThreshold} mg/m³ (+${chloroDelta} mg/m³ upwelling surge).`,
      impactScoreDelta: targetOvertakePoints
    });

    const simulatedZoneAInputs: CouncilInputs = {
      ...zoneA.inputs,
      waveHeight: scoreA >= scoreB ? waveThreshold : zoneA.inputs.waveHeight
    };
    const simulatedEvalA = this.evaluateCouncil({ latitude: 0, longitude: 0, isMarine: true }, simulatedZoneAInputs, { id: zoneA.id, name: zoneA.name });

    return {
      currentRanking: {
        zoneA: { id: zoneA.id, name: zoneA.name, score: scoreA },
        zoneB: { id: zoneB.id, name: zoneB.name, score: scoreB }
      },
      flipConditions,
      variableImpact: [
        { variable: 'Wave Height', sensitivity: 16.0, unit: 'pts / m' },
        { variable: 'Wind Velocity', sensitivity: 0.8, unit: 'pts / (km/h)' },
        { variable: 'Chlorophyll-a', sensitivity: 10.0, unit: 'pts / (mg/m³)' },
        { variable: 'SST Departure', sensitivity: 4.5, unit: 'pts / °C' }
      ],
      resultingScores: {
        zoneASimulated: simulatedEvalA.arbitration.finalScore,
        zoneBSimulated: scoreB,
        flipped: simulatedEvalA.arbitration.finalScore < scoreB
      },
      explanation: `To invert the current recommendation (${leader.name} at ${leader.score} vs ${trailer.name} at ${trailer.score}), the deterministic engine requires an environmental swing of at least ${targetOvertakePoints} points.`
    };
  }

  /**
   * "Challenge ORCA" Reasoning Engine
   * Answers challenges grounded strictly in council evidence
   */
  static challengeCouncil(
    evaluation: CouncilEvaluationResult,
    question: string
  ): CouncilChallengeResponse {
    const qLower = question.toLowerCase();
    const challengeId = `chal-${Date.now()}`;
    const evidenceReferenced: string[] = [];

    // Challenge: Which agent disagrees?
    if (qLower.includes('which agent') || qLower.includes('disagree')) {
      const diss = evaluation.disagreement;
      if (!diss.hasDisagreement) {
        return {
          challengeId,
          question,
          groundedAnswer: 'All 5 specialized reasoning modules (Weather, Ocean, Ecosystem, Risk, and Local Knowledge) unanimously agreed on this sector evaluation.',
          evidenceReferenced: ['Unanimous consensus across 5 domains'],
          confidenceScore: 98
        };
      }

      const dissenting = diss.dissentingAgents[0];
      const agentObj = evaluation.agents[dissenting];
      evidenceReferenced.push(...agentObj.evidence.map(e => `${e.metric}: ${e.value} ${e.unit}`));

      return {
        challengeId,
        question,
        groundedAnswer: `The ${agentObj.agentName} took a dissenting status (${agentObj.status}). Finding: "${agentObj.findings[0]}". While other domains report favorable baseline parameters, this specialist detected limiting physical exposure or localized variance.`,
        dissentingAgent: dissenting,
        evidenceReferenced,
        confidenceScore: agentObj.confidence
      };
    }

    // Challenge: What evidence is weakest?
    if (qLower.includes('weakest') || qLower.includes('least confident') || qLower.includes('missing')) {
      const agentEntries = Object.values(evaluation.agents).sort((a, b) => a.confidence - b.confidence);
      const weakest = agentEntries[0];
      const weakestEv = weakest.evidence[0];
      evidenceReferenced.push(`${weakest.agentName} confidence: ${weakest.confidence}%`, `${weakestEv.metric} (${weakestEv.source})`);

      return {
        challengeId,
        question,
        groundedAnswer: `The weakest evidence is within the ${weakest.agentName} at ${weakest.confidence}% confidence, relying on ${weakestEv.source}. While suitable for planning, potential satellite cloud-masking or spatial interpolation slightly increases uncertainty.`,
        weakestEvidence: weakestEv,
        evidenceReferenced,
        confidenceScore: weakest.confidence
      };
    }

    // Challenge: What could make this decision wrong?
    if (qLower.includes('wrong') || qLower.includes('error') || qLower.includes('fail')) {
      const negativeFactors = evaluation.arbitration.negativeFactors;
      evidenceReferenced.push(...negativeFactors);

      return {
        challengeId,
        question,
        groundedAnswer: `This recommendation could be invalidated if: (1) An unforecast convective squall causes wave height to exceed safe thresholds; (2) Nearshore bathymetric shoaling produces steep wave reflections not resolved in regional satellite grids; or (3) Subsurface thermal front dispersion moves the pelagic core further offshore.`,
        flipSuggestion: 'Monitor the change radar and refresh telemetry every 15 minutes during passage.',
        evidenceReferenced,
        confidenceScore: 92
      };
    }

    // Challenge: Why did you rank this zone higher?
    if (qLower.includes('why') || qLower.includes('rank') || qLower.includes('higher')) {
      const dominant = evaluation.arbitration.dominantFactors;
      evidenceReferenced.push(...dominant);

      return {
        challengeId,
        question,
        groundedAnswer: `This zone was ranked at ${evaluation.arbitration.finalScore}/100 based on three dominant deterministic factors: ${dominant.join('; ')}. The composite agreement of ${evaluation.arbitration.agreementLevel} confirms favorable operational margins under model version ${this.SCORING_MODEL_VERSION}.`,
        evidenceReferenced,
        confidenceScore: evaluation.arbitration.confidence
      };
    }

    // Default grounded answer
    const summary = evaluation.whyThisZone.summary;
    evidenceReferenced.push(...evaluation.arbitration.dominantFactors);

    return {
      challengeId,
      question,
      groundedAnswer: `Based on verified environmental telemetry: ${summary}. The ORCA Decision Council arbitrated a deterministic score of ${evaluation.arbitration.finalScore}/100 with ${evaluation.arbitration.confidence}% confidence (Model: ${this.SCORING_MODEL_VERSION}).`,
      evidenceReferenced,
      confidenceScore: evaluation.arbitration.confidence
    };
  }

  /**
   * Generates WHY THIS ZONE breakdown
   */
  private static generateWhyThisZone(agents: Record<CouncilAgentType, CouncilAgentEvaluation>) {
    const positiveEvidence: CouncilEvidenceItem[] = [];
    const negativeEvidence: CouncilEvidenceItem[] = [];

    Object.values(agents).forEach(a => {
      a.evidence.forEach(e => {
        if (e.contribution >= 0) {
          positiveEvidence.push(e);
        } else {
          negativeEvidence.push(e);
        }
      });
    });

    positiveEvidence.sort((a, b) => b.contribution - a.contribution);
    negativeEvidence.sort((a, b) => a.contribution - b.contribution);

    const summary = `Zone selected due to strong contributions from ${positiveEvidence.slice(0, 2).map(e => e.metric).join(' and ')}, balancing ${negativeEvidence.length > 0 ? negativeEvidence[0].metric : 'negligible risks'}.`;

    return {
      positiveEvidence,
      negativeEvidence,
      summary
    };
  }

  /**
   * Generates WHY NOT THIS ZONE comparison
   */
  private static generateWhyNotThisZone(
    inputsA: CouncilInputs,
    inputsB: CouncilInputs,
    compZoneId: string,
    compZoneName: string
  ) {
    const advantages: string[] = [];
    const disadvantages: string[] = [];

    if (inputsA.waveHeight < inputsB.waveHeight) {
      advantages.push(`Calmer sea state (${inputsA.waveHeight.toFixed(1)}m vs ${inputsB.waveHeight.toFixed(1)}m at ${compZoneName})`);
    } else if (inputsA.waveHeight > inputsB.waveHeight) {
      disadvantages.push(`Higher wave exposure (${inputsA.waveHeight.toFixed(1)}m vs ${inputsB.waveHeight.toFixed(1)}m at ${compZoneName})`);
    }

    if (inputsA.windSpeed < inputsB.windSpeed) {
      advantages.push(`Gentler operational wind (${inputsA.windSpeed.toFixed(0)} vs ${inputsB.windSpeed.toFixed(0)} km/h)`);
    } else if (inputsA.windSpeed > inputsB.windSpeed) {
      disadvantages.push(`Greater wind stress (${inputsA.windSpeed.toFixed(0)} vs ${inputsB.windSpeed.toFixed(0)} km/h)`);
    }

    if (inputsA.chlorophyll > inputsB.chlorophyll) {
      advantages.push(`Higher biological productivity (${inputsA.chlorophyll.toFixed(2)} vs ${inputsB.chlorophyll.toFixed(2)} mg/m³)`);
    } else if (inputsA.chlorophyll < inputsB.chlorophyll) {
      disadvantages.push(`Lower biomass concentration (${inputsA.chlorophyll.toFixed(2)} vs ${inputsB.chlorophyll.toFixed(2)} mg/m³)`);
    }

    const summary = `Primary trade-off: ${compZoneName} offers alternative environmental balance but exhibits ${disadvantages.length > 0 ? disadvantages[0] : 'different geographic exposure'}.`;

    return {
      comparisonZoneId: compZoneId,
      comparisonZoneName: compZoneName,
      advantages,
      disadvantages,
      summary
    };
  }
}
